name: PR (Full)

# PRs touching react-router-dev will also run on Windows and OSX

on:
  pull_request:
    paths:
      - pnpm-lock.yaml
      - integration/**
      - packages/react-router-dev/**
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-firefox:
    name: 👀 Integration Test
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: ubuntu-24.04
      node_version: '[22]'
      browser: '["firefox"]'

  integration-msedge:
    name: 👀 Integration Test
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: windows-2025
      node_version: '[22]'
      browser: '["msedge"]'

  integration-webkit:
    name: 👀 Integration Test
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: macos-15
      node_version: '[22]'
      browser: '["webkit"]'
